name: C CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest
    compiler: gcc-latest

    strategy:
      matrix:
        cc: ['12']
        deps: ['enabled']
        platform: ['x64', 'x86'] 

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Make

      run: make
