name: C CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        cc: ['12']
        deps: ['enabled']
        platform: ['x64', 'x86'] 

    steps:
   - name: Setup GCC
     uses: Dup4/actions-setup-gcc@v1
       with:
       version: latest

    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Make
      run: make
