name: On PRs - meson

on: pull_request

concurrency:
  group: ${{github.workflow}}-${{github.head_ref}}
  cancel-in-progress: true

jobs:
  Ubuntu:
    runs-on: ubuntu-latest
    name: Linux-GCC${{matrix.cc}}-deps=${{matrix.deps}}
    strategy:
      matrix:
        cc: ['gcc-latest']
        deps: ['enabled', 'disabled']
        platform: ['x64', 'x86'] 
    steps:
      - uses: actions/checkout@v3

      - name: Install packages
        run: |
          sudo apt install -y gcc-${{matrix.cc}}
          python3 -m pip install meson ninja

      - name: Compile and Test
        env:
          CC: gcc-${{matrix.cc}}
        run: |
          meson setup "${{github.workspace}}/build" -Dauto_features=${{matrix.deps}} -Dwarning_level=3
          meson compile -C "${{github.workspace}}/build" --verbose
          meson test -C "${{github.workspace}}/build" --verbose
